# Inspired by:
# https://hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/
# https://github.com/gpakosz/.tmux/blob/master/.tmux.conf
# https://www.youtube.com/watch?v=jcrE1qrm_e8

set -g base-index 1          # start with window/pane 1 
set -g pane-base-index 1     # (easier to go between 1,2,3 than 0,1,2)
set -g prefix2 C-s           # Set leader to CTRL+S (easier than CTRL+B)

setw -g automatic-rename on  # rename windows to reflect the current program
set -g renumber-windows on   # renumber windows when a window is closed

# reload config file
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Enable mouse control
set -g mouse on

# Open new windows in the current path
bind c new-window -c "#{pane_current_path}"

# Use full terminal colour space
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# allow focus events to get through to applications running tmux
set -g focus-events on

# ----- Navigation -----

# vim bindings
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+

set -g @vim_navigator_prefix_mapping_clear_screen ""

# pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_text " #W"

# ------ Plugins ------
# press CTRL-S SHIFT-I to install plugins
# press CTRL-S alt-U to uninstall plugins

# List of plugins
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g status-position top

set -g status-left-length 200
set -gF status-left "#{@catppuccin_status_gitmux}"

set -g status-right-length 100
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set -ag status-right "#{E:@catppuccin_status_time}"

set -g @catppuccin_date_time_text " %H:%M"
set -ag status-right "#{E:@catppuccin_status_date_time}"

# Initialize TMUX plugin manager (keep at very bottom of the file)
run '~/.tmux/plugins/tpm/tpm'

